/* Configuration for gnatcoll_json generated by Alire */
#ifndef GNATCOLL_JSON_CONFIG_H
#define GNATCOLL_JSON_CONFIG_H

#define CRATE_VERSION "1.4.2-dev"
#define CRATE_NAME "gnatcoll_json"

#define ALIRE_HOST_OS "linux"

#define ALIRE_HOST_ARCH "x86_64"

#define ALIRE_HOST_DISTRO "fedora"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  3

#endif
